var lightTheme = function () {
    $("body").css("background", "#fafafa")
    $("td").css("border", "1px #fafafa solid")
    $("td").css("background", "#f5f5f5")
    $("th").css("border", "1px #fafafa solid")
    $("th").css("background", "#ddd")
    $("a").css("color", "black")
    $("h1").css("color", "#a1a1a1")
    $("h2").css("color", "#a1a1a1")
    $("h3").css("color", "#a1a1a1")
    $("h4").css("color", "black")
    $("h5").css("color", "black")
    $(".gray").css("color", "#a1a1a1")
    $(".ph").css("color", "#448aff")
    $(".grayDark").css("background", "none")
    $(".grayLight").css("background", "#b8b8b8")
    $(".split").css("background", "linear-gradient(to top right,#ddd 49.5%,#fafafa 49.5%,#fafafa 50.5%,#ddd 50.5%)")
    $("#menu").css("background", "#f5f5f5")
    $("#menu").find("a").css("color", "black")
    $("#menu").find("a").addClass("light")
    $("#settingsButton").attr("src", "../../gfx/settingsLight.png")
    $("#contentDiv").css("color", "black")
}
var darkTheme = function () {
    $("body").css("background", "#111")
    $("td").css("border", "1px #111 solid")
    $("td").css("background", "#333")
    $("th").css("border", "1px #111 solid")
    $("th").css("background", "#222")
    $("a").css("color", "white")
    $("h1").css("color", "#707070")
    $("h2").css("color", "#707070")
    $("h3").css("color", "#707070")
    $("h4").css("color", "white")
    $("h5").css("color", "white")
    $(".gray").css("color", "#707070")
    $(".ph").css("color", "#6aa3ff")
    $(".grayDark").css("background", "#474747")
    $(".grayLight").css("background", "none")
    $(".split").css("background", "linear-gradient(to top right,#222 49.5%,#111 49.5%,#111 50.5%,#222 50.5%)")
    $("#menu").css("background", "#222")
    $("#menu").find("a").css("color", "white")
    $("#menu").find("a").removeClass("light")
    $("#settingsButton").attr("src", "../../gfx/settingsDark.png")
    $("#contentDiv").css("color", "white")
}
