var lightTheme = function () {
    $("body").css("background", "#eeeeee")
    $("a").css("color", "black")
    $("h3").css("color", "#a1a1a1")
    $("#menu").css("background", "#ddd")
    $("#menu").find("a").css("color", "black")
    $("#menu").find("a").addClass("light")
    $("#total").css("color", "black")
    $("#guessed").css("color", "black")
    $("#prompt").css("color", "black")
    $("#inputArea").css("color", "#a1a1a1")
    $("#inputArea").css("background", "#ddd")
    $("#range").css("background", "#ddd")
    $("#rangeWord").css("color", "black")
    $(".rangeMove").css("color", "black")
    $(".rangeMove").css("background", "#ddd")
    $("path").addClass("light")
}
var darkTheme = function () {
    $("body").css("background", "#111")
    $("a").css("color", "white")
    $("h3").css("color", "#707070")
    $("#menu").css("background", "#222")
    $("#menu").find("a").css("color", "white")
    $("#menu").find("a").removeClass("light")
    $("#total").css("color", "white")
    $("#guessed").css("color", "white")
    $("#prompt").css("color", "white")
    $("#inputArea").css("color", "#707070")
    $("#inputArea").css("background", "#222")
    $("#range").css("background", "#474747")
    $("#rangeWord").css("color", "white")
    $(".rangeMove").css("color", "white")
    $(".rangeMove").css("background", "#222")
    $("path").removeClass("light")
}
